name: ping-loop
# Стартуємо вручну один раз → далі job сама себе перезапускає
on:
  workflow_dispatch:

permissions:
  actions: write     # дозвіл, щоб викликати gh workflow run
  contents: read

concurrency:
  group: ping-loop
  cancel-in-progress: false   # новий запуск чекає завершення попереднього

jobs:
  loop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # відновлюємо CSV із Secret у файл
      - name: Restore endpoints.csv from secret
        run: echo "$ENDPOINTS_CSV" > endpoints.csv
        env:
          ENDPOINTS_CSV: ${{ secrets.ENDPOINTS_CSV }}

      - name: Install Python deps
        run: pip install --quiet requests

      - name: Call endpoints
        run: python ping.py

      # 4 год 10 хв (15 000 с) + випадковий jitter 0-10 хв
      - name: Wait 4 h 10 m + random jitter
        run: |
          BASE=15000                 # 4 год 10 хв
          JITTER=$(( RANDOM % 601 )) # 0-600 с
          SLEEP=$(( BASE + JITTER ))
          echo "Sleeping $SLEEP seconds"
          sleep "$SLEEP"

      # самозапуск
      - name: Trigger next run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ping-loop.yml --ref ${{ github.ref }}
